scaffold-templates/README.md

linked files from README.md with updated formatting
files werent linked in the readme.md
updated formatting to link files
links!

Update README.md with file links

---

.github/fileUpdater/action.yml
.github/fileUpdater/update.sh
.github/findRepos/action.yml
.github/findRepos/find.sh
.github/workflows/updateStringInRepos.yml

Workflow for updating strings in tagged repo

ci: update tagged repos

---

.github/workflows/updateStringInRepos.yml

ci: change folder location

---

.github/workflows/updateStringInRepos.yml

ci: add checkout

---

.github/workflows/updateStringInRepos.yml

ci: action location

---

.github/findRepos/action.yml

ci: string output

---

.github/findRepos/action.yml

ci: more quotes

---

.github/findRepos/find.sh

ci: remove extra echo

---

.github/fileUpdater/action.yml

ci: file vs filename

---

.github/actions.md

docs: docs about actions and workflows

---

CODEOWNERS.md

Explain the context and why you're making that change. What is the problem
you're trying to solve? In some cases there is not a problem and this can be
thought of being the motivation for your change.
Describe the modifications you've done.
What will change as a result of your pull request? Note that sometimes this
section is unnecessary because it is self-explanatory based on the solution.
* Describe what was done; not the result 
* Use the active voice 
* Use the present tense 
* Capitalize properly 
* Do not end in a period — this is a title/subject 
* Prefix the subject with its scope
(Write your test plan here. If you changed any code, please provide us with
clear instructions on how you verified your changes work.)

Created a CODEOWNERS.md file

---

cookiecutter.json

Explain the context and why you're making that change. What is the problem
you're trying to solve? In some cases there is not a problem and this can be
thought of being the motivation for your change.
Describe the modifications you've done.
What will change as a result of your pull request? Note that sometimes this
section is unnecessary because it is self-explanatory based on the solution.
* Describe what was done; not the result 
* Use the active voice 
* Use the present tense 
* Capitalize properly 
* Do not end in a period — this is a title/subject 
* Prefix the subject with its scope
(Write your test plan here. If you changed any code, please provide us with
clear instructions on how you verified your changes work.)

Revised questions based on our first user testing sesh

---

README.md
tier0/{{cookiecutter.project_slug}}/README.md
tier1/{{cookiecutter.project_slug}}/README.md
tier2/{{cookiecutter.project_slug}}/README.md
tier3/{{cookiecutter.project_slug}}/README.md
tier4/{{cookiecutter.project_slug}}/README.md

There are a couple of miscellaneous updates we'd like to make to the README that came up while outbounding DedupliFHIR.
- Added one-liner referring to LICENSE file in Public Domain section
- Updated Security Policy section with vulnerability submission description and SECURITY.md oneliner
- Added comment guidance from Tier 4 to Tier 3 sections

README.md Updates

---

CODEOWNERS.md
tier1/{{cookiecutter.project_slug}}/CODEOWNERS.md
tier2/{{cookiecutter.project_slug}}/CODEOWNERS.md
tier3/{{cookiecutter.project_slug}}/CODEOWNERS.md
tier4/{{cookiecutter.project_slug}}/CODEOWNERS.md

The current CODEOWNERS.md is not standardized across all tiers
- Added comments/guidance from Tier 4 file to all tiers
- Minor Capitalization edits

CODEOWNERS.md: Added Comments + Minor Edits

---

tier1/{{cookiecutter.project_slug}}/README.md
tier2/{{cookiecutter.project_slug}}/README.md
tier3/{{cookiecutter.project_slug}}/README.md
tier4/{{cookiecutter.project_slug}}/README.md

As per @decause-gov and I's discussion, we are making another round of revisions to all tiers of the README.
- Added Project Vision as a subsection of "About the Project" to all tiers
- Added Agency Mission & Team Mission as subsection of "About the Project" for Tier 2 projects since projects in this tier are home-run
- Removed "multiple languages" from community section
- Removed core team section in Tier 2

README Updates: About The Project Subsections and Minor Revisions

---

tier2/{{cookiecutter.project_slug}}/CODE_OF_CONDUCT.md
tier2/{{cookiecutter.project_slug}}/COMMUNITY_GUIDELINES.md

As per our discussion, we decided to add COMMUNITY_GUIDELINES.md & CODE_OF_CONDUCT.md to our Tier 2 maturity model level. 
Added COMMUNITY_GUIDELINES.md & CODE_OF_CONDUCT.md

Added COMMUNITY_GUIDELINES.md & CODE_OF_CONDUCT.md to Tier 2

---

tier4/{{cookiecutter.project_slug}}/CODEOWNERS.md
tier4/{{cookiecutter.project_slug}}/COMMUNITY_GUIDELINES.md
tier4/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier4/{{cookiecutter.project_slug}}/GOVERNANCE.md
tier4/{{cookiecutter.project_slug}}/MAINTAINERS.md
tier4/{{cookiecutter.project_slug}}/README.md

Due to updates made to the maturity model from outbounding DedupliFHIR, the Tier 4 templates need to be reviewed to ensure they align with newest changes.
- Cleaned up comments
- Removed line about Justice40 in COMMUNITY_GUIDELINES.md

Tier 4 Template Review

---

tier0/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier0/{{cookiecutter.project_slug}}/README.md

Due to updates made to the maturity model from outbounding DedupliFHIR, the Tier 0 templates need to be reviewed to ensure they align with newest changes.
- Added Recommended sections to README.md
- Created CONTRIBUTING.md and added Recommended sections
- Cleaned up templates

Tier 0 Template Review

---

tier2/{{cookiecutter.project_slug}}/CODEOWNERS.md
tier2/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier2/{{cookiecutter.project_slug}}/README.md

Due to updates made to the maturity model from outbounding DedupliFHIR, the Tier 2 templates need to be reviewed to ensure they align with newest changes.
- Added missing Shipping Releases section
- Commented out Recommended sections (PR, Team Guidelines, Documentation)
- Added missing comments and cleaned up templates

Tier 2 Template Review

---

tier1/cookiecutter.json
tier1/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier1/{{cookiecutter.project_slug}}/repometrics/hooks/post_gen_project.sh
tier1/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json
tier4/cookiecutter.json
tier4/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier4/{{cookiecutter.project_slug}}/repometrics/hooks/post_gen_project.sh
tier4/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json

Currently, we want to add metrics to the repo reports that include where it is hosted, project fisma level, project type, etc. We will be using this to create tags in the reports and help create visualizations.
Created a cookiecutter template that asks multiple choice and free response questions, the code.json will be generated inside the project that is created by cookiecutter and moved to parent directory.

Add Repometrics to Tier 4

---

tier1/cookiecutter.json
tier1/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier1/{{cookiecutter.project_slug}}/repometrics/hooks/post_gen_project.sh
tier1/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json
tier3/cookiecutter.json
tier3/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier3/{{cookiecutter.project_slug}}/repometrics/hooks/post_gen_project.sh
tier3/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json
tier4/cookiecutter.json
tier4/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier4/{{cookiecutter.project_slug}}/repometrics/hooks/post_gen_project.sh
tier4/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json

Currently, we want to add metrics to the repo reports that include where it is hosted, project fisma level, project type, etc. We will be using this to create tags in the reports and help create visualizations.
Created a cookiecutter template that asks multiple choice and free response questions, the code.json will be generated inside the project that is created by cookiecutter and moved to parent directory.

Add Repometrics to Tier 3

---

.github/extendJSON/action.yml
.github/extendJSON/resolve.py
.github/workflows/extendJSONFile.yml

When using `repo-scaffolder` for an existing repo I noticed that the `checks.yml` file was failing to run.
Comments inline. It was a bit of a journey, sorry for all the commits.
I was able to run this and had a working checks action.
(Write your test plan here. If you changed any code, please provide us with
clear instructions on how you verified your changes work.)

Fixes for checks.yml

---

tier0/{{cookiecutter.project_slug}}/README.md
tier1/{{cookiecutter.project_slug}}/README.md
tier2/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier2/{{cookiecutter.project_slug}}/README.md
tier3/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier3/{{cookiecutter.project_slug}}/GOVERNANCE.md
tier3/{{cookiecutter.project_slug}}/MAINTAINERS.md
tier3/{{cookiecutter.project_slug}}/README.md
tier4/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier4/{{cookiecutter.project_slug}}/GOVERNANCE.md
tier4/{{cookiecutter.project_slug}}/MAINTAINERS.md
tier4/{{cookiecutter.project_slug}}/README.md

Inspired by https://github.com/DSACMS/dedupliFHIR/pull/74, I installed a spell check VScode extension which identified misspellings in the markdown files.
Fixed misspellings in various markdown files across all tiers.

Docs: Fix misspellings

---

tier1/{{cookiecutter.project_slug}}/SECURITY.md
tier2/{{cookiecutter.project_slug}}/SECURITY.md
tier3/{{cookiecutter.project_slug}}/SECURITY.md
tier4/{{cookiecutter.project_slug}}/SECURITY.md

The CMS VDP has been updated to reflect the launch of our new bug bounty program! As a result, SECURITY.md needs to be updated accordingly.
Updated SECURITY.md for all the tiers to reflect below:
https://www.cms.gov/about-cms/information-systems/privacy/vulnerability-disclosure-policy

SECURITY.md: New VDP policy

---

tier0/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier0/{{cookiecutter.project_slug}}/README.md
tier1/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier1/{{cookiecutter.project_slug}}/README.md
tier2/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier2/{{cookiecutter.project_slug}}/README.md
tier3/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier3/{{cookiecutter.project_slug}}/README.md
tier4/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier4/{{cookiecutter.project_slug}}/README.md

The CMS VDP has been updated to reflect the launch of our new bug bounty program! As a result, README.md and SECURITY.md needs to be updated accordingly.
Updated README.md & CONTRIBUTING.md for all the tiers to reflect below:
https://www.cms.gov/about-cms/information-systems/privacy/vulnerability-disclosure-policy

README.md & CONTRIBUTING.md: Updated VDP reporting text

---

CONTRIBUTING.md
README.md
SECURITY.md
tier1/{{cookiecutter.project_slug}}/SECURITY.md
tier2/{{cookiecutter.project_slug}}/SECURITY.md
tier3/{{cookiecutter.project_slug}}/SECURITY.md
tier4/{{cookiecutter.project_slug}}/SECURITY.md

The CMS VDP has been updated to reflect the launch of our new bug bounty program! As a result, READ.md and CONTRIBUTING.md needs to be updated accordingly.
Removed contact email. Added updated VDP guidance to README.md and CONTRIBUTING.md

Docs: Added updated VDP text to Security sections

---

README.md

Update instructions on creating code.json + fixed typos

Update instructions on creating code.json + fixed typos

---

.github/workflows/checks.yml

We'd like to run repolinter on the repository
Create checks.yml repolinter workflow

Workflows: Create checks.yml repolinter workflow

---

tier2/checklist.md

converted Tier 2 checklist into a markdown document.

Tier 2 checklist markdown

---

.github/extendJSON/resolve.py

Currently, the extendJSON action recurses through the `extends` field and simply returns the base `repolinter.json` aka the Tier 1 `repolinter.json`. As a result, when running this action to fetch `repolinter.json` for Tiers 2-4, the Tier 1 `repolinter.json` is returned with no integration of the Tier2-4 rulesets.
When fetching the Tier 2-4 `repolinter.json`, we should merge the rulesets.
Using `pydash`, we merge the rulesets defined for Tier 2-4 into the base tier 1 `repolinter.json`, producing the correct and complete `repolinter.json` for that tier.
extendsJSON action now produces the correct and complete `repolinter.json` for the tier inputted.
In the `extendJSON` directory in `.github`, 
run `python resolve.py https://raw.githubusercontent.com/DSACMS/repo-scaffolder/main/tier4/%7B%7Bc …

Repolinter: ExtendJSON action merges rulesets to produce repolinter.json for tier inputted

---

tier1/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml
tier2/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml
tier3/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml
tier4/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml

Based on this [issue](https://github.cms.gov/orgs/DSAC/projects/13/views/1?pane=issue&itemId=486), we want to enable secret scanning for our repos.
There was a GH Action in the marketplace that automates this so we just add it to our templates.
Secret scanning will occur on every push and pull request.
Added the same .yml file to a different repo and tested there.

Added gitleaks Workflow

---

.github/workflows/checks.yml

changed syntax so workflow can run

changed syntax

---

CODEOWNERS.md
MAINTAINERS.md

- When viewing the changes of this Pull Request, files and sections have been added in order to bring this repository up to standards.
- Using either this GitHub page or an IDE, please fill in the section with the proper information that is missing.
- The body of the section will provide context and examples of how it should be filled out.
---
<details>
<summary>
Repolinter Results
</summary>
*This report was generated automatically by the Repolinter.*
This Repolinter run generated the following results:
| ❗  Error | ❌  Fail | ⚠️  Warn | ✅  Pass | Ignored | Total |
|---|---|---|---|---|---|
| 0 | 2 | 2 | 60 | 0 | 64 |
- [Fail](#user-content-fail)
- [❌ `maintainers-contains-maintainers-list`](#user-content--maintainers-contains-maintainers-list)
- [❌ …

Repolinter Results
