DSACMS/repo-scaffolder

tier3/{{cookiecutter.project_slug}}/CODE_OF_CONDUCT.md
tier3/{{cookiecutter.project_slug}}/COMMUNITY_GUIDELINES.md
tier4/{{cookiecutter.project_slug}}/CODE_OF_CONDUCT.md
tier4/{{cookiecutter.project_slug}}/COMMUNITY_GUIDELINES.md

Tier 3 & 4 projects require guidance around community governance however we were lacking these policies until now.
We have created new `CODE_OF_CONDUCT.md` and `COMMUNITY_GUIDELINES`files based off the USDS Justice 40 project.`GOVERNANCE.md` point to these files.
When running this tool, it will generate these files for tiers 3 & 4 going forward.

Added CODE_OF_CONDUCT.md and COMMUNITY_GUIDELINES.md to Tier 3 + 4

---

CONTRIBUTING.md
tier1/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier2/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier3/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier4/{{cookiecutter.project_slug}}/CONTRIBUTING.md

Based on our discussions outbounding the DedupliFHIR repository, we decided to reduce the content in the Security and Responsible Disclosure policies section.
Updated Security and Responsible Disclosure policies section to:
- Only include the vulnerability submission section
- Include a one-liner that points to the `SECURITY.md` file

Updating Security Policy section in CONTRIBUTING.md

---

tier2/{{cookiecutter.project_slug}}/MAINTAINERS.md
tier3/{{cookiecutter.project_slug}}/MAINTAINERS.md

Currently, there is no `MAINTAINERS.md` file for Tier 2. The current Tier 3 `MAINTAINERS.md` is actually the Tier 2 version. Additionally, the Tier 3 `MAINTAINERS.md` is missing a table with information on member roles and responsibilities.
- Added Tier 2 `MAINTAINERS.md`
- Updated Tier 3 `MAINTAINERS.md`, taken from: https://github.com/DSACMS/dedupliFHIR/blob/main/MAINTAINERS.md?plain=1
- Added member roles and responsibilities table to Tier 3.

Updated MAINTAINERS.md file for Tier 2 and Tier 3

---

.github/workflows/autoMergeMainIntoDev.yml

Before,  it was possible for `main` to get ahead of the `dev` branch and cause problems for people wanting to contribute to `dev` without first creating a PR. 
With this new workflow, `dev` will always be up to date with `main` and the workflow will be available for anyone to use.

Add Workflow to Auto-Merge `main` into `dev` 

---

tier0/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier0/{{cookiecutter.project_slug}}/README.md
tier1/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier1/{{cookiecutter.project_slug}}/README.md
tier2/{{cookiecutter.project_slug}}/COMMUNITY_GUIDELINES.md
tier2/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier2/{{cookiecutter.project_slug}}/README.md
tier3/{{cookiecutter.project_slug}}/COMMUNITY_GUIDELINES.md
tier3/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier3/{{cookiecutter.project_slug}}/README.md
tier4/{{cookiecutter.project_slug}}/COMMUNITY_GUIDELINES.md
tier4/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier4/{{cookiecutter.project_slug}}/README.md

Throughout the past couple of weeks, we have been making extensive updates to markdown templates in all tiers. We would like to sluggify the updated templates with existing variables from cookiecutter.json.
README.md
- Added `project_name` and `project_description` variables at top
CONTRIBUTING.md
- Updated branches with `project_org` and `project_repo_name` variables in Workflow and Branching section
- Updated links with `project_org` and `project_repo_name` variables in Documentation section
- Added `project_name` variable
COMMUNITY_GUIDELINES
- Added `project_name` variable

Cookiecutter: Sluggify updated templates with existing variables

---

maturity-model-tiers.md
tier1/{{cookiecutter.project_slug}}/repolinter.json
tier2/{{cookiecutter.project_slug}}/MAINTAINERS.md
tier3/{{cookiecutter.project_slug}}/MAINTAINERS.md

Identified minor fixes to templates now that repolinter.json files are merged
Fixes include:
- `code-owners-contains-repo-domains` level changed to off in tier 1 since `CODEOWNERS.md` is not recommended for Tier 1
- Added missing "Headers:" to Tier 2 `MAINTAINERS.md` fulfill repolinter check
- Reformatted headers in `MAINTAINERS.md`
- Fixed spacing

Templates: Minor Fixes

---

CONTRIBUTING.md

The Pull Request Policy is inaccurate and out of date in CONTRIBUTING.md. This repository is stored on public facing GitHub and not our enterprise GitHub instance. As a result, the policy differs and pull requests are reviewed more normally. 
Changed the pull request policy to reflect how review is currently carried out.

Update Pull Request Policy on CONTRIBUTING.md

---

tier0/hooks/post_gen_project.py
tier1/hooks/post_gen_project.py
tier2/hooks/post_gen_project.py

In tiers 0, 1, and 2, when being asked the following:
```
[7/8] Would you like to create a repo on github.com?
1 - True
2 - False
Choose from [1/2] (1): 2
[8/8] Would you like to receive updates from ...
1 - True
2 - False
Choose from [1/2] (1): 2
```
Selecting false proceeds to be true anyway, because in the
hook, the Python variable is actually a string and so the truthy value
of "False" is True.
I changed `if CREATE_REPO:` to `if CREATE_REPO == "True":`.
Now, selecting False for those two prompts will not proceed to
run the hook functions as unintended.

fix post gen project hook bug in tiers 0-2

---

tier2/{{cookiecutter.project_slug}}/.github/workflows/contributors.yml
tier3/{{cookiecutter.project_slug}}/.github/workflows/contributors.yml
tier4/{{cookiecutter.project_slug}}/.github/workflows/contributors.yml

When running cookiecutter for this repo the following error is produced:
`Unable to create file '.github/workflows/contributors.yml'
Error message: 'secrets' is undefined`
Similar to #99. 
When this patch was applied I was successfully able to use cookiecutter.
Tested on a repo I was creating.

Fix Jinja template problem with secrets in Github actions

---

tier1/cookiecutter.json
tier1/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier1/{{cookiecutter.project_slug}}/repometrics/hooks/post_gen_project.sh
tier1/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json

Currently, we want to add metrics to the repo reports that include where it is hosted, project fisma level, project type, etc. We will be using this to create tags in the reports and help create visualizations.
Created a cookiecutter template that asks multiple choice and free response questions, the code.json will be generated inside the project that is created by cookiecutter and moved to parent directory.

Add Repometrics to Tier 1

---

.github/workflows/extendJSONFile.yml

When using the `repo-scaffolder` I was receiving the following error message in the `checks.yml`:
``` Invalid workflow file
error parsing called workflow
".github/workflows/checks.yml"
-> "DSACMS/repo-scaffolder/.github/workflows/extendJSONFile.yml@add-repolinter-workflows" (source branch with sha:f06340f5e852f5ac242bf492d7930e7a3d376481)
: workflow is not reusable as it is missing a `on.workflow_call` trigger
```
Add the `workflow_call` trigger to the yml file.
Should be able to use the workflow now.

Add workflow_call trigger to workflow

---

tier3/{{cookiecutter.project_slug}}/.github/workflows/repoStructure.yml
tier3/{{cookiecutter.project_slug}}/README.md
tier4/{{cookiecutter.project_slug}}/.github/workflows/repoStructure.yml
tier4/{{cookiecutter.project_slug}}/README.md

Currently, developers have to manually input their project's repository
structure in the README.
This Github Action automatically generates the directory structure in the
relevant part of the README by using the `tree` Bash command.

Add tree repo structure GH Action

---

tier1/{{cookiecutter.project_slug}}/.github/workflows/checks.yml

When using repo-scaffolder to create a new Tier 1 project, an error occurred due to the checks.yml file failing to create. `needs:` is undefined.
Added raw json tag to `needs.resolve-repolinter-json.outputs.raw-json`. Fix is similar to https://github.com/DSACMS/repo-scaffolder/pull/99
Project generation for Tier 1 are successfully created now

Tier 1: Fix for project generation due to error in checks.yml

---

tier1/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier1/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json
tier2/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier2/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json
tier3/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier3/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json
tier4/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier4/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json

Currently in cookiecutter, we ask the user to select maturity model. There is a chance users can pick the wrong maturity model. Based on number selected, it is stored in the maturity_model_tier variable in code.json. 
Remove maturity_model_tier question in cookiecutter.json, and add tier directly based on directory/tier.
Reducing chances of incorrect/misleading metadata.

Remove Maturity Model Cookiecutter Prompt

---

tier1/{{cookiecutter.project_slug}}/.github/workflows/checks.yml
tier2/{{cookiecutter.project_slug}}/.github/workflows/checks.yml
tier3/{{cookiecutter.project_slug}}/.github/workflows/checks.yml
tier4/{{cookiecutter.project_slug}}/.github/workflows/checks.yml

The checks.yml file was not working when I was trying to use it on my recently generated [repodive-tools repository 
](https://github.com/DSACMS/repodive-tools). It was failing to create the label for the desired issue properly.
Also, it doesn't make sense to run the checks.yml on pull requests because it is an action that is supposed to update an issue and issues are supposed to releflect the canon state of the project. If we run it on pending changes then the issue won't make sense. 
Make the workflow run on push to main. Also use the main version of the `extendJSONFile` workflow instead of the dev version that didn't work. Also, add a standard api key to use for this action as a secret in the DSACMS org. I also removed the label logic from the checks.yml file because it wasn't working.

Fix Issues With Checks.yml workflow 

---

tier0/{{cookiecutter.project_slug}}/README.md
tier1/{{cookiecutter.project_slug}}/README.md
tier2/{{cookiecutter.project_slug}}/README.md
tier3/{{cookiecutter.project_slug}}/README.md
tier4/{{cookiecutter.project_slug}}/README.md

We would like to add information about a repository's SBOM as part of our repository hygenine standards.
Added text about what an SBOM is, link to the EO/policy, and the repository's dependency graph to the README templates in all tiers.

README: Added SBOM excerpt to policies section

---

code.json
tier1/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier1/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json
tier2/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier2/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json
tier3/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier3/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json
tier4/{{cookiecutter.project_slug}}/repometrics/cookiecutter.json
tier4/{{cookiecutter.project_slug}}/repometrics/{{cookiecutter.project_type}}/code.json

Per code.json best practices and patterns, we fields should be camel case, not snake case.
Updated fields for cookiecutter to camel case, and updated fields in repo-scaffolder's code.json to reflect these patterns. Added `Docs` to project types.

Camel Case code.json Fields

---

tier1/README.md
tier2/README.md
tier3/README.md
tier4/README.md

As we work on the CMS Open Source Policy, we are looking to link to some sections of `repo-scaffolder` to it. Currently, our only document that explains the maturity model tiers is `maturity-model-tiers.md` and it does so in a brief way. We would like to improve documentation on the maturity model framework so users have a clear idea on the characteristics and differences of the tiers.
Created a README.md to every tier that includes:
- Description of maturity model tier
- List of important characteristics
- Table with required and recommended files

Added a README.md to every tier

---

tier2/{{cookiecutter.project_slug}}/.github/workflows/auto-changelog.yml
tier2/{{cookiecutter.project_slug}}/MAINTAINERS.md
tier3/{{cookiecutter.project_slug}}/.github/workflows/auto-changelog.yml
tier3/{{cookiecutter.project_slug}}/MAINTAINERS.md
tier4/{{cookiecutter.project_slug}}/.github/workflows/auto-changelog.yml
tier4/{{cookiecutter.project_slug}}/MAINTAINERS.md

When generating Tier 2-4 projects using cookiecutter, this error occurs:
Added raw tags to the workflow and `MAINTAINERS.md` files
Solution is similar to https://github.com/DSACMS/repo-scaffolder/pull/99.
Running cookiecutter on tiers 2-4 now exit cleanly without an error.
`cookiecutter . --directory=X` where X = 2, 3, 4

Workflows: Fixes to `autochangelog.yml` workflow files in tiers 2-4

---

release-guidelines-template.md
tier2/{{cookiecutter.project_slug}}/MAINTAINERS.md
tier3/{{cookiecutter.project_slug}}/MAINTAINERS.md
tier4/{{cookiecutter.project_slug}}/MAINTAINERS.md

There are some links in the release guidance docs that have links in the format [text][url] instead of the proper [text](url).
Fix the issue by formatting the links correctly.

Fix Markdown Links in Release Guidance Documentation 

---

release-guidelines-template.md

We currently do not credit the source of where we got the structure of our release documentation. Our release documentation is a heavily altered version of the one found in the openmobilityfoundaiton's governance repo: https://github.com/openmobilityfoundation/governance/blob/main/technical/ReleaseGuidelines.md
Credit the inspiration for the format, layout, and general structure of our release guidance documentation.
I have added a link to the release documentation that I used as an inspiration to write the release documentation found in this repository.

Update release-guidelines-template.md to Add Credit

---

tier0/hooks/post_gen_project.py
tier1/hooks/post_gen_project.py
tier2/hooks/post_gen_project.py
tier3/hooks/post_gen_project.py
tier4/hooks/post_gen_project.py

When I use repo-scaffolder to create a fresh new repository and then use the cookiecutter command to create the repo's code.json file, the "created" field in the date object is incorrect.
Create a .git directory whenever each cookiecutter is run by default.
The date object within code.json is correct.
* Language for the commit message for the first commit might need to change to fit the changelog language.
* Related to #181 
Tested locally

Fixed the dateCreated Bug

---

tier1/checklist.md
tier2/checklist.md
tier3/checklist.md
tier4/checklist.md

Now that `code.json` is implemented, we would like to incorporate this into our outbound checklists.
Created a new section on Reviewing Project Metadata to all checklists. This includes information on the purpose of `code.json` and instructions on how to create code.json.
PR also includes typo and spacing fixes so all checklists have consistent formatting.

Docs: Adding Reviewing Project Metadata section to all checklists + clean up

---

.github/workflows/checks.yml

run-checks repolinter workflow is not working due to invalid personal access token
Updated personal access token value.

Merge Dev into Main

---

tier0/{{cookiecutter.project_slug}}/README.md
tier1/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
tier1/{{cookiecutter.project_slug}}/README.md
tier2/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
tier3/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
tier4/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py

Based on #194, when using cookiecutter to generate code.json, the multi-select fields values are formatted incorrectly.
- Added a string formatter in post_gen to format the output properly.
- Corrected link.
- code.json multi-select fields outputs in the proper format.
- Links are now usable.
Tested locally.

Fixed Multi-Select Fields Formatting and Fixed Broken Link

---

tier0/README.md
tier0/{{cookiecutter.project_slug}}/README.md

We should have a README.md to explain what Tier 0 is. Other tiers have this but not Tier 0 at the moment.
- Created a README.md explaining the characteristics and required/recommended files of Tier 0.
- Renamed to Core Team, this is a recommended section so commented it out
- Renamed section to Local Development, this is a recommended section so commented it out

Docs: Created a README.md for Tier 0 and minor edits

---

requirements.txt

Currently, the tool uses cookiecutter 2.4.0, 
Updated cookiecutter to 2.6.0 which is the latest version release
Tested all cookiecutter prompts and works fine!

Cookiecutter: Updated Cookiecutter to use latest release 2.6.0

---

tier1/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
tier2/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
tier3/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
tier4/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py

Overall, labor_hour value is pretty high because it is taking into account the markdown files. We would like to exclude this from the calculation.
Included a flag in the scc command that excludes md files.
A decrease in laborHours
* Issue #196 
* We can add more files that we want to exclude to fine tune this
Tested locally and each tier showed a decrease in labor hours

Fixed laborHours Calculations

---

.github/extendJSON/action.yml

Getting an error in most recent job that pydash doesn't exist: https://github.com/DSACMS/repo-scaffolder/actions/runs/11902303164/job/33167039818. I realized I forgot to add a step in the GitHub action to install dependencies.
Added a step to install dependencies

Repolinter: Updated extendJSON action to include installing dependencies

---

tier1/{{cookiecutter.project_slug}}/README.md
tier1/{{cookiecutter.project_slug}}/repolinter.json

Repolinter.json needed to be edited to support the new PR action.
Added `file-name` and `file-content` within each rule in Tier 1. Since the rest of the Tiers inherit from Tier 1, all tiers have access to `file-name` and `file-content`
Repolinter PR Actions can be used successfully with reposcaffolder. 
- to view what this would look like in an actual PR, view this: 
- https://github.com/sachin-panayil/sachinpanayil-usdc-2024/pull/1496/files
- https://github.com/DSACMS/repolinter-actions/pull/4/files
- this is easier to see the changes that were made

Edit Repolinter Configurations for Repolinter PR Action 

---

tier1/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml
tier2/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml
tier3/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml
tier4/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml

Came across this bug while creating a new repo:
```
Unable to create file '.github/workflows/gitleaks.yml'
Error message: 'secrets' is undefined
Context: {
"_cookiecutter": {
"add_maintainer": [
true,
false
],
"code_owners": "Git usernames of code owners; separated by commas.",
"create_repo": [
true,
false
],
"project_description": "This is the project description, could match github.com repo description.",
"project_name": "My Project",
"project_org": "DSACMS",
"project_repo_name": "{{ cookiecutter.project_name.lower().replace(' ', '-') }}",
"project_slug": "{{ cookiecutter.project_name.lower().replace(' ', '_') }}",
"project_visibility": [
"public",
"internal",
"private"
],
"receive_updates": [
true,
false
]
},
"cookiecutter": {
"_checkout": null,
"_copy_without_render": [ …
```

Workflows: Fix gitleaks workflow template conflict

---

.github/extendJSON/action.yml

ExtendJSON was failing
Specify the required shell.
Job no longer fails. 
Test with [nektos/act](https://github.com/nektos/act): 
`doas act -s GITHUB_TOKEN="$(gh auth token)"`

Fix ExtendJSON: add shell property

---

.github/workflows/checks.yml
tier1/{{cookiecutter.project_slug}}/.github/workflows/checks.yml
tier1/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml
tier2/{{cookiecutter.project_slug}}/.github/workflows/checks.yml
tier2/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml
tier3/{{cookiecutter.project_slug}}/.github/workflows/checks.yml
tier3/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml
tier4/{{cookiecutter.project_slug}}/.github/workflows/checks.yml
tier4/{{cookiecutter.project_slug}}/.github/workflows/gitleaks.yml

- gitleaks required a license key to work within an org
- repolinter didnt use the new PR action
- use a new gitleaks action that doesnt require a license
- change the action that used repolinter
- gitleaks works
- repolinter check pushes a PR instead of an issue
* this needs to get merged in order to solve #223 
- run actions locally

Changed gitleaks and repolinter workflows

---

.github/docs/workflows.md
CODEOWNERS.md
CODE_OF_CONDUCT.md
COMMUNITY_GUIDELINES.md
CONTRIBUTING.md
GOVERNANCE.md
MAINTAINERS.md
README.md

- When viewing the changes of this Pull Request, files and sections have been added in order to bring this repository up to standards.
- Using either this GitHub page or an IDE, please fill in the section with the proper information that is missing.
- The body of the section will provide context and examples of how it should be filled out.
---
<details>
<summary>
Repolinter Results
</summary>
*This report was generated automatically by the Repolinter.*
This Repolinter run generated the following results:
| ❗  Error | ❌  Fail | ⚠️  Warn | ✅  Pass | Ignored | Total |
|---|---|---|---|---|---|
| 0 | 19 | 8 | 37 | 0 | 64 |
- [Fail](#user-content-fail)
- [❌ `maintainers-file-exists`](#user-content--maintainers-file-exists)
- [❌ `community-guidelines-file-exists`](#user-content--community-guidel …

Repolinter Results

---

MAINTAINERS.md
tier1/hooks/post_gen_project.py
tier2/hooks/post_gen_project.py
tier3/hooks/post_gen_project.py
tier4/hooks/post_gen_project.py

While testing prod, I found a bug where .git directory was being created in `.github` instead of the project-level directory.
Edited post-gen hook to move location of the working directory back to project level directory before .git initialization occurs.
- When running `cookiecutter . --directory=tierX`, .git is created in project directory and successfully has initial commit in git log
Tested locally.

Cookiecutter: Fix .git initalization bug during repo creation

---

tier2/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier3/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier4/{{cookiecutter.project_slug}}/CONTRIBUTING.md

There is insufficient guidance on releases in the CONTRIBUTING.md file in tier 4. 
Add the link to the relevant file.

Update CONTRIBUTING.md to include MAINTAINERS.md link

---

tier2/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier3/{{cookiecutter.project_slug}}/CONTRIBUTING.md
tier4/{{cookiecutter.project_slug}}/CONTRIBUTING.md

Addresses the following observed exception:
File "CONTRIBUTING.md", line 332, in template
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
File "CONTRIBUTING.md", line 332
token: ${{{{ secrets.GITHUB_TOKEN }}}}
Proposed syntax change in order for the template to be rendered for the line in 
question  as:
token: ${{ secrets.GITHUB_TOKEN }}
The proposed template modification resolves the TemplateSyntaxError issue.
cookiecuter is v2.6.0, jinja2 is v3.1.6
Verified this resolves the issue locally with:
cookiecutter -f ./repo-scaffolder --directory=tier3

Addresses jinja2.exceptions.TemplateSyntaxError

---

assets/css/styles.css
index.html

We would like to tie all 3 components of our repo-scaffolder stack together by creating a new section: "How a Repository Becomes a Project"
Created new section. For now, it includes a checklist of the components of a health open source project. We will add more content soon!
To link directly to section: https://dsacms.github.io/repo-scaffolder/#repo-to-project
`python3 -m http.server 8000` to run locally and looks great!

Landing Page: Add how a repo becomes a project section
